apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logretriever
  namespace: logging-system
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
