apiVersion: v1
kind: Service
metadata:
  name: logretriever
  namespace: logging-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: logretriever
  type: NodePort
